if(EXISTS "/home/diego/ufsc/modsim/Genesys-Simulator/build-demo/source/tests/unit/genesys_test_statistics[1]_tests.cmake")
  include("/home/diego/ufsc/modsim/Genesys-Simulator/build-demo/source/tests/unit/genesys_test_statistics[1]_tests.cmake")
else()
  add_test(genesys_test_statistics_NOT_BUILT genesys_test_statistics_NOT_BUILT)
endif()
