#include "CppSerializer.h"

#include <cassert>
#include <cctype>
#include <vector>
#include <memory>
#include <algorithm>
#include <utility>
#include <set>
#include <unordered_map>

#include "Simulator.h"

#define INDENT "\t"

CppSerializer::CppSerializer(Model* model) :
    _model(model) {
    assert(model != nullptr);
}

PersistenceRecord* CppSerializer::newPersistenceRecord() {
    return new PersistenceRecord(*_model->getPersistence());
}

static std::string indent(int times = 1) {
    std::string str = "";
    for (int i = 0; i < times; ++i) {
        str += INDENT;
    }
    return str;
}

static std::string cppIdentifier(const std::string& text, const std::string& fallback) {
    std::string result;
    result.reserve(text.size());
    for (const unsigned char ch : text) {
        result += std::isalnum(ch) ? static_cast<char>(ch) : '_';
    }
    if (result.empty()) {
        result = fallback;
    }
    if (!result.empty() && std::isdigit(static_cast<unsigned char>(result.front()))) {
        result.insert(result.begin(), '_');
    }
    return result;
}

static std::string uniqueCppIdentifier(const std::string& text, const std::string& fallback,
                                       std::set<std::string>* usedIdentifiers) {
    std::string candidate = cppIdentifier(text, fallback);
    std::string unique = candidate;
    unsigned int suffix = 1;
    while (usedIdentifiers->count(unique) != 0u) {
        unique = candidate + "_" + std::to_string(suffix++);
    }
    usedIdentifiers->insert(unique);
    return unique;
}

static std::string cppStringLiteral(const std::string& text) {
    std::string escaped;
    escaped.reserve(text.size() + 2);
    for (const char ch : text) {
        switch (ch) {
        case '\\':
            escaped += "\\\\";
            break;
        case '"':
            escaped += "\\\"";
            break;
        case '\n':
            escaped += "\\n";
            break;
        case '\r':
            escaped += "\\r";
            break;
        case '\t':
            escaped += "\\t";
            break;
        default:
            escaped += ch;
            break;
        }
    }
    return "\"" + escaped + "\"";
}

static bool shouldEmitSimulationControl(SimulationControl* control) {
    if (control == nullptr || control->isReadOnly()) {
        return false;
    }
    // Object and list controls require model-specific creation/removal context; keep
    // C++ export focused on scalar controls that can be restored safely by value.
    return !control->getIsClass() && !control->getIsList();
}

static ModelDataDefinition* findSerializedElement(Model* model, const std::string& type,
                                                  const Util::identification id,
                                                  const std::string& name,
                                                  const bool isComponent) {
    if (model == nullptr) {
        return nullptr;
    }
    if (isComponent) {
        ModelComponent* component = model->getComponentManager()->find(id);
        if (component == nullptr && !name.empty()) {
            component = model->getComponentManager()->find(name);
        }
        return component;
    }
    ModelDataDefinition* data = model->getDataManager()->getDataDefinition(type, id);
    if (data == nullptr && !name.empty()) {
        data = model->getDataManager()->getDataDefinition(type, name);
    }
    return data;
}

bool CppSerializer::dump(std::ostream& output) {
    // prelude
    output << indent(0) << "/*\n";
    output << indent(0) << " * This C++ program was automatically generated by Genesys " + _model->getParentSimulator()
        ->getVersion() + "\n";
    output << indent(0) << " * For your own safety, please review this file before compiling and running it.\n";
    output << indent(0) << " */\n";
    output << indent(0) << "\n";

    // gather parts in ID-order
    std::set<std::string> datadefs;
    std::set<std::string> components;
    std::set<std::string> typenames;
    std::vector<std::unique_ptr<PersistenceRecord>> parts;
    for_each([&](auto name) {
        if (name == "SimulatorInfo" || name == "Simulator" || name == "ModelInfo" || name == "ModelSimulation")
            return
                0;
        auto fields = std::unique_ptr<PersistenceRecord>(newPersistenceRecord());
        get(name, fields.get());
        typenames.insert(fields->loadField("typename"));
        parts.push_back(std::move(fields));
        return 0;
    });

    // do includes and separate defs/components
    std::set<std::string> includes;
    // Iterate over a value snapshot of class names to collect include dependencies for persisted data definitions.
    std::list<std::string> dataDefinitionClassnames = _model->getDataManager()->getDataDefinitionClassnames();
    for (auto& klass : dataDefinitionClassnames) {
        if (!typenames.count(klass)) continue;
        datadefs.insert(klass);
        includes.insert(_model->getParentSimulator()->getPluginManager()->sourceIncludePathFor(klass));
    }
    for (auto& comp : *_model->getComponentManager()->getAllComponents()) {
        if (!typenames.count(comp->getClassname())) continue;
        components.insert(comp->getClassname());
        includes.insert(_model->getParentSimulator()->getPluginManager()->sourceIncludePathFor(comp->getClassname()));
    }
    output << indent(0) << "#include \"kernel/simulator/Simulator.h\"\n";
    output << indent(0) << "#include <memory>\n";
    output << indent(0) << "#include <stdexcept>\n";
    output << indent(0) << "#include <string>\n";
    for (auto& path : includes) {
        if (!path.empty()) {
            output << indent(0) << "#include \"" + path + "\"\n";
        }
    }
    output << indent(0) << "\n";

    output << indent(0) << "static void setProperty(ModelDataDefinition* element, const std::string& propertyName, const std::string& value) {\n";
    output << indent(1) << "if (element == nullptr) {\n";
    output << indent(2) << "throw std::runtime_error(\"Cannot set property on null model element\");\n";
    output << indent(1) << "}\n";
    output << indent(1) << "for (SimulationControl* control : *element->getSimulationControls()->list()) {\n";
    output << indent(2) << "if (control == nullptr || control->getName() != propertyName) {\n";
    output << indent(3) << "continue;\n";
    output << indent(2) << "}\n";
    output << indent(2) << "if (control->getIsEnum()) {\n";
    output << indent(3) << "std::unique_ptr<List<std::string>> options(control->getStrValues());\n";
    output << indent(3) << "if (options != nullptr) {\n";
    output << indent(4) << "unsigned int index = 0;\n";
    output << indent(4) << "for (const std::string& option : *options->list()) {\n";
    output << indent(5) << "if (option == value) {\n";
    output << indent(6) << "control->setValue(std::to_string(index));\n";
    output << indent(6) << "return;\n";
    output << indent(5) << "}\n";
    output << indent(5) << "++index;\n";
    output << indent(4) << "}\n";
    output << indent(3) << "}\n";
    output << indent(2) << "}\n";
    output << indent(2) << "control->setValue(value);\n";
    output << indent(2) << "return;\n";
    output << indent(1) << "}\n";
    output << indent(1) << "throw std::runtime_error(\"SimulationControl not found: \" + propertyName);\n";
    output << indent(0) << "}\n";
    output << indent(0) << "\n";

    std::unordered_map<Util::identification, std::string> identifiersById;
    std::unordered_map<std::string, std::string> identifiersByName;
    std::set<std::string> usedIdentifiers;
    for (auto& var : parts) {
        const std::string type = var->loadField("typename");
        const Util::identification id = var->loadField("id", -1);
        const std::string name = var->loadField("name", "_" + type + "_" + std::to_string(id));
        const std::string identifier = uniqueCppIdentifier(name, "_" + type + "_" + std::to_string(id),
                                                           &usedIdentifiers);
        identifiersById[id] = identifier;
        identifiersByName[name] = identifier;
    }

    output << indent(0) << "int main(int argc, char** argv) {\n";
    output << indent(1) << "// instantiate simulator\n";
    output << indent(1) << "Simulator* genesys = new Simulator();\n";
    output << indent(1) << "genesys->getTraceManager()->setTraceLevel(TraceManager::Level::L2_results);\n";
    output << indent(1) << "PluginManager* plugins = genesys->getPluginManager();\n";
    output << indent(1) << "\n";
    output << indent(1) << "// create model\n";
    output << indent(1) << "Model* model = genesys->getModelManager()->newModel();\n";
    output << indent(1) << "// model->load(\"model.gen\")\n";
    output << indent(1) << "\n";

    output << indent(1) << "// initialize model parts\n";
    for (auto& var : parts) {
        std::string type = var->loadField("typename");
        Util::identification id = var->loadField("id", -1);
        std::string name = var->loadField("name", "_" + type + "_" + std::to_string(id));
        const std::string identifier = identifiersById[id];
        output << indent(1) // << (name.find(".") != std::string::npos ? "// " : "")
            << type + "* " + identifier + " = plugins->newInstance<" + type + ">(model, " +
            cppStringLiteral(name) + ");\n";
    }
    output << indent(1) << "\n";

    output << indent(1) << "// restore scalar properties\n";
    for (auto& var : parts) {
        const std::string type = var->loadField("typename");
        const Util::identification id = var->loadField("id", -1);
        const std::string name = var->loadField("name", "_" + type + "_" + std::to_string(id));
        const std::string identifier = identifiersById[id];
        ModelDataDefinition* element = findSerializedElement(_model, type, id, name, components.count(type) != 0u);
        if (element == nullptr || element->getSimulationControls() == nullptr) {
            continue;
        }
        for (SimulationControl* control : *element->getSimulationControls()->list()) {
            if (!shouldEmitSimulationControl(control)) {
                continue;
            }
            output << indent(1) << "setProperty(" + identifier + ", " + cppStringLiteral(control->getName()) +
                ", " + cppStringLiteral(control->getValue()) + ");\n";
        }
    }
    output << indent(1) << "\n";

    output << indent(1) << "// connect model components\n";
    ComponentManager* cm = _model->getComponentManager();
    for (auto& var : parts) {
        std::string type = var->loadField("typename");
        if (!components.count(type)) continue;
        Util::identification id = var->loadField("id", -1);
        ModelComponent* component = cm->find(id);
        if (component == nullptr) continue;
        std::string origin = identifiersById[id];
        //
        unsigned short nextSize = var->loadField("nexts", 1);
        for (unsigned short i = 0; i < nextSize; i++) {
            // target id
            Util::identification nextId = var->loadField("nextId" + Util::StrIndex(i), 0);
            if (nextSize == 1) nextId = var->loadField("nextId", static_cast<unsigned int>(nextId));
            // id -> component
            ModelComponent* nextComponent = cm->find(nextId);
            if (nextComponent == nullptr) {
                _model->getTracer()->traceError("found unregistered target ID " + std::to_string(nextId));
                return false;
            }
            // target port
            unsigned short nextPort = var->loadField("nextinputPortNumber" + Util::StrIndex(i), 0);
            // connect
            auto target = identifiersById[nextComponent->getId()];
            output << indent(1)
                // << (origin.find(".") != std::string::npos || target.find(".") != std::string::npos ? "// " : "")
                << origin + "->connectTo(" + target + ", " + std::to_string(nextPort) + ");\n";
        }
    }
    output << indent(1) << "\n";

    output << indent(1) << "// set simulation parameters\n";
    auto sim = _model->getSimulation();
    output << indent(1) << "ModelSimulation* sim = model->getSimulation();\n";
    output << indent(1) << "sim->setNumberOfReplications(" + std::to_string(sim->getNumberOfReplications()) +
        ");\n";
    output << indent(1) << "sim->setReplicationLength(" + std::to_string(sim->getReplicationLength()) +
        ", Util::TimeUnit::" + Util::StrTimeUnitLong(sim->getReplicationLengthTimeUnit()) + ");\n";
    output << indent(1) << "sim->setReplicationReportBaseTimeUnit(Util::TimeUnit::" + Util::StrTimeUnitLong(
        sim->getReplicationBaseTimeUnit()) + ");\n";
    output << indent(1) << "\n";

    output << indent(1) << "// run the simulation\n";
    output << indent(1) << "sim->setShowReportsAfterSimulation(true);\n";
    output << indent(1) << "sim->start();\n";
    output << indent(1) << "\n";

    output << indent(1) << "// free memory\n";
    output << indent(1) << "delete genesys;\n";
    output << indent(1) << "\n";

    output << indent(1) << "return 0;\n";
    output << indent(0) << "}\n";

    return true;
}

bool CppSerializer::load(std::istream& input) {
    return false;
} // never

bool CppSerializer::get(const std::string& name, PersistenceRecord* entry) {
    assert(entry != nullptr);
    auto key = name == "Simulator" ? "SimulatorInfo" : name;

    auto it = _metaobjects.find(key);
    if (it != _metaobjects.end()) {
        entry->insert(it->second->begin(), it->second->end());
        return true;
    }

    it = _components.find(key);
    if (it == _components.end()) return false;
    entry->insert(it->second->begin(), it->second->end());
    return true;
}

bool CppSerializer::put(const std::string name, const std::string type, const Util::identification id,
                        PersistenceRecord* fields) {
    // copy fields
    assert(fields != nullptr);
    auto saved = std::unique_ptr<PersistenceRecord>(this->newPersistenceRecord());
    saved->insert(fields->begin(), fields->end());

    // enforce consistency
    if (type == "") return false;
    auto unaliased = type == "Simulator" ? "SimulatorInfo" : type;
    saved->saveField("typename", unaliased);
    saved->saveField("id", id);

    // choose partition
    if (id == 0) {
        _metaobjects[unaliased] = std::move(saved);
    }
    else {
        if (id != 0) saved->saveField("name", name);
        _components[name] = std::move(saved);
    }

    return true;
}

int CppSerializer::for_each(std::function<int(const std::string&)> delegate) {
    // enfore id-order
    std::vector<std::pair<bool, std::string>> sorted;
    sorted.reserve(_metaobjects.size() + _components.size());
    for (auto& entry : _metaobjects) sorted.push_back({true, entry.first});
    for (auto& entry : _components) sorted.push_back({false, entry.first});
    std::sort(sorted.begin(), sorted.end(), [&](auto& a, auto& b) {
        if (a.first && b.first) {
            // both metatypes
            return this->_metaobjects.at(a.second)->loadField("id", 0) < this->_metaobjects.at(b.second)->
                                                                               loadField("id", 0);
        }
        else if (!a.first && !b.first) {
            return this->_components.at(a.second)->loadField("id", -1) < this->_components.at(b.second)->
                                                                               loadField("id", -1);
        }
        else /* different origins? metatypes < components */ {
            return a.first && !b.first;
        }
    });

    // then do the user-level iteration
    for (auto& e : sorted) {
        int stop = delegate(e.second);
        if (stop) return stop;
    }
    return 0;
}
