#include "services/CppModelExporter.h"

// This include gives access to generated Qt widgets where generated C++ text is displayed.
// These includes provide kernel model APIs used by C++ code generation.
#include "../../../../kernel/simulator/Simulator.h"
#include "../../../../kernel/simulator/Model.h"
#include "../../../../kernel/simulator/ModelSimulation.h"
#include "../../../../kernel/simulator/ModelComponent.h"
#include "../../../../kernel/simulator/ConnectionManager.h"
#include "../../../../kernel/simulator/ModelDataDefinition.h"
#include "../../../../kernel/util/List.h"
#include "../../../../kernel/util/Util.h"

// This include provides QString conversion APIs used by the target text widget.
#include <QPlainTextEdit>
#include <QString>

// These includes provide STL containers and utilities used by code assembly.
#include <map>
#include <utility>


// Store simulator and output editor used by C++ export rendering.
CppModelExporter::CppModelExporter(Simulator* simulator, QPlainTextEdit* cppCodeEditor)
    : _simulator(simulator)
    , _cppCodeEditor(cppCodeEditor) {
}

std::string CppModelExporter::addCppCodeLine(const std::string& line, unsigned int indent) const {
    // This block preserves tab-indentation semantics used by existing generated output.
    std::string text;
    for (unsigned int i = 0; i < indent; i++) {
        text += "\t";
    }
    text += line + "\n";
    return text;
}

void CppModelExporter::actualizeModelCppCode() const {
    // This guard preserves safety when dependencies are missing.
    if (_simulator == nullptr || _cppCodeEditor == nullptr) {
        return;
    }

    // This block preserves generation flow only when a model is currently loaded.
    Model* m = _simulator->getModelManager()->current();
    if (m != nullptr) {
        unsigned short tabs = 0;
        std::string text;
        std::string text2;
        std::string name;
        // Store generated code sections in automatic storage to avoid temporary heap allocations.
        std::map<std::string, std::string> code;

        // This block preserves generated file banner section.
        text = addCppCodeLine("/*");
        text += addCppCodeLine(" * This C++ source code was automatically generated by GenESyS");
        text += addCppCodeLine(" */");
        code.insert({"1begin", text});

        // This block preserves include generation semantics for components and data definitions.
        text = addCppCodeLine("#include \"kernel/simulator/Simulator.h\"");
        text = addCppCodeLine("#include \"kernel/simulator/PropertyGenesys.h\"");
        // Track already-included symbols in an automatic list and reuse it across include generation.
        List<std::string> included;
        for (ModelComponent* comp : *m->getComponentManager()->getAllComponents()) {
            name = comp->getClassname();
            if (included.find(name) == included.list()->end()) {
                included.insert(name);
                text += addCppCodeLine("#include \"plugins/components/" + name + ".h\"");
            }
        }
        // Iterate over a value snapshot of data-definition class names to remove manual delete semantics.
        for (std::string ddClassname : m->getDataManager()->getDataDefinitionClassnames()) {
            text += addCppCodeLine("#include \"plugins/data/" + ddClassname + ".h\"");
            for (ModelDataDefinition* modeldata : *m->getDataManager()->getDataDefinitionList(ddClassname)->list()) {
                name = modeldata->getName();
                if (name.find(".") == std::string::npos) {
                    if (included.find(name) == included.list()->end()) {
                        included.insert(ddClassname);
                        text += addCppCodeLine("#include \"plugins/data/" + ddClassname + "\"");
                    }
                }
            }
        }
        code.insert({"2include", text});

        // This block preserves generated main function preamble.
        text = addCppCodeLine("\nint main(int argc, char** argv) {");
        tabs++;
        text += addCppCodeLine("// Create simulator, a property editor, a model and get acess to plugins", tabs);
        text += addCppCodeLine("Simulator* genesys = new Simulator();", tabs);
        text += addCppCodeLine("PropertyEditorGenesys* propertyEditor = new PropertyEditorGenesys();", tabs);
        text += addCppCodeLine("Model* model = genesys->getModels()->newModel();", tabs);
        text += addCppCodeLine("PluginManager* plugins = genesys->getPlugins();", tabs);
        text += addCppCodeLine("model->getTracer()->setTraceLevel(TraceManager::TraceLevel::L9_mostDetailed);", tabs);
        code.insert({"3main", text});

        // This block preserves generation of data definition instantiation and property assignment.
        text = addCppCodeLine("// Create model components and setting properties", tabs);
        // Iterate over a value snapshot of class names when emitting data-definition construction code.
        for (std::string ddClassname : m->getDataManager()->getDataDefinitionClassnames()) {
            for (ModelDataDefinition* modeldata : *m->getDataManager()->getDataDefinitionList(ddClassname)->list()) {
                name = modeldata->getName();
                if (name.find(".") == std::string::npos) {
                    text += addCppCodeLine(ddClassname + "* " + name + " = plugins->newInstance<" + ddClassname + ">(model, \"" + name + "\");", tabs);
                }
                for (auto prop : *modeldata->getProperties()->list()) {
                    text += addCppCodeLine("SimulationControl* property = propertyEditor->findProperty(" + std::to_string(modeldata->getId()) + ", " + prop->getName() + ");", tabs);
                    text += addCppCodeLine("propertyEditor->changeProperty(property, " + prop->getValue() + ", false);", tabs);
                }
                text += addCppCodeLine("", tabs);
            }
        }
        code.insert({"4datadef", text});

        // This block preserves generation of model component instantiation statements.
        text = addCppCodeLine("// Create model components", tabs);
        for (ModelComponent* comp : *m->getComponentManager()->getAllComponents()) {
            name = comp->getName();
            if (name.find(".") == std::string::npos) {
                text += addCppCodeLine(comp->getClassname() + "* " + name + " = plugins->newInstance<" + comp->getClassname() + ">(model, \"" + name + "\");", tabs);
            }
        }
        code.insert({"5modelcompdef", text});

        // This block preserves generation of component connection statements.
        text = addCppCodeLine("// Connect the components in the model", tabs);
        for (ModelComponent* comp : *m->getComponentManager()->getAllComponents()) {
            name = comp->getName();
            if (name.find(".") == std::string::npos) {
                for (std::pair<unsigned int, Connection*> pair : *comp->getConnectionManager()->connections()) {
                    Connection* conn = pair.second;
                    text2 = conn->component->getName();
                    text += addCppCodeLine(name + "->getConnections()->insertAtPort(" + std::to_string(pair.first) + "," + text2 + ");", tabs);
                }
            }
        }
        code.insert({"6modelconnect", text});

        // This block preserves generation of simulation configuration statements.
        ModelSimulation* sim = m->getSimulation();
        text = addCppCodeLine("// Define simulation options", tabs);
        text += addCppCodeLine("ModelSimulation* sim = model->getSimulation();", tabs);
        text += addCppCodeLine("sim->setReplicationLength(" + std::to_string(sim->getReplicationLength()) + ")", tabs);
        text += addCppCodeLine("sim->setReplicationLengthTimeUnit(Util::TimeUnit::" + Util::StrTimeUnitLong(sim->getReplicationLengthTimeUnit()) + ");", tabs);
        text += addCppCodeLine("sim->setWarmUpPeriod(" + std::to_string(sim->getWarmUpPeriod()) + ");", tabs);
        text += addCppCodeLine("sim->setWarmUpPeriodTimeUnit(Util::TimeUnit::" + Util::StrTimeUnitLong(sim->getWarmUpPeriodTimeUnit()) + ");", tabs);
        text += addCppCodeLine("sim->setReplicationReportBaseTimeUnit(Util::TimeUnit::" + Util::StrTimeUnitLong(sim->getReplicationBaseTimeUnit()) + ");", tabs);
        text2 = sim->isShowReportsAfterSimulation() ? "true" : "false";
        text += addCppCodeLine("sim->setsetShowReportsAfterSimulation(" + text2 + ");", tabs);
        code.insert({"7simulation", text});

        // This block preserves generated execution trailer section.
        text = addCppCodeLine("// simulate and show report", tabs);
        text += addCppCodeLine("sim->start();", tabs);
        text += addCppCodeLine("return 0;", tabs);
        tabs--;
        text += addCppCodeLine("}", tabs);
        code.insert({"8end", text});

        // This block preserves final rendering order into the C++ code editor pane.
        _cppCodeEditor->clear();
        // Render generated code sections preserving lexical ordering by section key.
        for (std::pair<std::string, std::string> codeSection : code) {
            _cppCodeEditor->appendPlainText(QString::fromStdString(codeSection.second));
        }
    }
}
