/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   DiffEquations.cpp
 * Author: Prof. Rafael Luiz Cancian, Dr. Eng.
 * 
 * Created on
 */

#include "plugins/components/Continuous/DiffEquations.h"
#include "../../../kernel/simulator/model/Model.h"
//#include "kernel/simulator/Simulator.h"
//#include "kernel/simulator/PluginManager.h"
#include "plugins/data/Logic/Variable.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <dlfcn.h>
#include <string>
#include <vector>

namespace {

bool isIdentifierChar(char c) {
	return std::isalnum(static_cast<unsigned char>(c)) != 0 || c == '_';
}

std::string substituteStateVariablesInExpression(const std::string& expression,
                                                 const std::vector<std::string>& stateVariableNames) {
	std::string result = expression;
	std::vector<size_t> indices(stateVariableNames.size());
	for (size_t i = 0; i < indices.size(); ++i) {
		indices[i] = i;
	}
	// sort by descending name length so a longer name like "vel" is replaced before a
	// shorter prefix like "v", preventing partial substitutions inside longer identifiers
	std::sort(indices.begin(), indices.end(), [&](size_t a, size_t b) {
		return stateVariableNames[a].length() > stateVariableNames[b].length();
	});
	for (size_t idx : indices) {
		const std::string& name = stateVariableNames[idx];
		if (name.empty()) {
			continue;
		}
		const std::string replacement = "y[" + std::to_string(idx) + "]";
		size_t pos = 0;
		while (pos < result.size()) {
			const size_t found = result.find(name, pos);
			if (found == std::string::npos) {
				break;
			}
			const bool leftOk = (found == 0) || !isIdentifierChar(result[found - 1]);
			const bool rightOk = (found + name.size() >= result.size())
			                     || !isIdentifierChar(result[found + name.size()]);
			if (leftOk && rightOk) {
				result.replace(found, name.size(), replacement);
				pos = found + replacement.size();
			} else {
				pos = found + 1;
			}
		}
	}
	return result;
}

std::vector<std::string> resolveStateVariableNames(List<std::string>* stateNames,
                                                   unsigned int equationCount) {
	std::vector<std::string> names;
	if (stateNames != nullptr && stateNames->size() == equationCount) {
		for (unsigned int i = 0; i < equationCount; i++) {
			names.push_back(stateNames->getAtRank(i));
		}
	}
	if (names.empty()) {
		for (unsigned int i = 0; i < equationCount; i++) {
			names.push_back("x" + std::to_string(i));
		}
	}
	return names;
}

std::string buildDiffEquationsSource(const std::string& componentName,
                                     const std::vector<std::string>& stateVariableNames,
                                     List<std::string>* equations,
                                     double maxSteps) {
	const unsigned int n = equations->size();
	std::string sourceCode =
	        "//\n"
	        "// File automatically generated by GenESyS DiffEquations plugin\n"
	        "// Component: " + componentName + "\n"
	        "//\n"
	        "#include <cmath>\n"
	        "#include <cstring>\n"
	        "\n"
	        "static const int N = " + std::to_string(n) + ";\n"
	        "static const int MAX_STEPS = " + std::to_string(static_cast<int>(maxSteps)) + ";\n"
	        "\n"
	        "static void derivatives(double t, const double* y, double* dydt) {\n"
	        "\t(void)t;\n";
	for (unsigned int i = 0; i < n; i++) {
		const std::string substituted =
		        substituteStateVariablesInExpression(equations->getAtRank(i), stateVariableNames);
		sourceCode += "\tdydt[" + std::to_string(i) + "] = " + substituted + ";\n";
	}
	sourceCode +=
	        "}\n"
	        "\n"
	        "static void rk4_step(double t, double h, double* y) {\n"
	        "\tdouble k1[N], k2[N], k3[N], k4[N], ytmp[N], f[N];\n"
	        "\tderivatives(t, y, f);\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\tk1[i] = h * f[i];\n"
	        "\t}\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\tytmp[i] = y[i] + 0.5 * k1[i];\n"
	        "\t}\n"
	        "\tderivatives(t + 0.5 * h, ytmp, f);\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\tk2[i] = h * f[i];\n"
	        "\t}\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\tytmp[i] = y[i] + 0.5 * k2[i];\n"
	        "\t}\n"
	        "\tderivatives(t + 0.5 * h, ytmp, f);\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\tk3[i] = h * f[i];\n"
	        "\t}\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\tytmp[i] = y[i] + k3[i];\n"
	        "\t}\n"
	        "\tderivatives(t + h, ytmp, f);\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\tk4[i] = h * f[i];\n"
	        "\t}\n"
	        "\tfor (int i = 0; i < N; ++i) {\n"
	        "\t\ty[i] += (k1[i] + 2.0 * k2[i] + 2.0 * k3[i] + k4[i]) / 6.0;\n"
	        "\t}\n"
	        "}\n"
	        "\n"
	        "extern \"C\" void onDispatchEvent(double* stateVars, int n, double t0,\n"
	        "                                double tTarget, double step) {\n"
	        "\tif (stateVars == nullptr || n != N || step <= 0.0 || tTarget < t0) {\n"
	        "\t\treturn;\n"
	        "\t}\n"
	        "\tdouble y[N];\n"
	        "\tstd::memcpy(y, stateVars, static_cast<size_t>(N) * sizeof(double));\n"
	        "\tdouble t = t0;\n"
	        "\tint steps = 0;\n"
	        "\twhile (t + step <= tTarget + 1e-15 && steps < MAX_STEPS) {\n"
	        "\t\trk4_step(t, step, y);\n"
	        "\t\tt += step;\n"
	        "\t\t++steps;\n"
	        "\t}\n"
	        "\tif (t < tTarget - 1e-15 && steps < MAX_STEPS) {\n"
	        "\t\trk4_step(t, tTarget - t, y);\n"
	        "\t\tt = tTarget;\n"
	        "\t}\n"
	        "\tstd::memcpy(stateVars, y, static_cast<size_t>(N) * sizeof(double));\n"
	        "}\n";
	return sourceCode;
}

} // namespace


// Externalize function GetPluginInformation to be accessible throught dynamic linked library
#ifdef PLUGINCONNECT_DYNAMIC
extern "C" StaticGetPluginInformation GetPluginInformation() {
	return &DiffEquations::GetPluginInformation;
}
#endif


//
// public: //! constructors
//

DiffEquations::DiffEquations(Model* model, std::string name) : ModelComponent(model, Util::TypeOf<DiffEquations>(), name) {
}


//
// public: //! new public user methods for this component
//

List<std::string> *DiffEquations::getEquations() const {
	return _equations;
}

List<std::string> *DiffEquations::getStateVariableNames() const {
	return _stateVariableNames;
}

double DiffEquations::getfinalTime() const {
	return _finalTime;
}

void DiffEquations::setFinalTime(double newFinalTime) {
	_finalTime = newFinalTime;
}

double DiffEquations::getmaxSteps() const {
	return _maxSteps;
}

void DiffEquations::setMaxSteps(double newMaxSteps) {
	_maxSteps = newMaxSteps;
}

double DiffEquations::getprecision() const {
	return _precision;
}

void DiffEquations::setPrecision(double newPrecision) {
	_precision = newPrecision;
}

List<double> *DiffEquations::getvaluesOnFinalTime() const {
	return _valuesOnFinalTime;
}

// ...


//
// public: //! virtual methods
//

std::string DiffEquations::show() {
	return ModelComponent::show() + "";
}


//
// public: //! static methods that must have implementations (Load and New just the same. GetInformation must provide specific infos for the new component
//

PluginInformation* DiffEquations::GetPluginInformation() {
	PluginInformation* info = new PluginInformation(Util::TypeOf<DiffEquations>(), &DiffEquations::LoadInstance, &DiffEquations::NewInstance);
	info->setCategory("Continuous");
	//info->setMinimumInputs(1);
	//info->setMinimumOutputs(1);
	//info->setMaximumInputs(1);
	//info->setMaximumOutputs(1);
	//info->setSource(false);
	//info->setSink(false);
	//info->setSendTransfer(false);
	//info->setReceiveTransfer(false);
	info->insertDynamicLibFileDependence("cppcompiler.so");
	//info->setDescriptionHelp("//@TODO");
	//info->setAuthor("...");
	//info->setDate("...");
	//info->setObservation("...");
	return info;
}

ModelComponent* DiffEquations::LoadInstance(Model* model, PersistenceRecord *fields) {
	DiffEquations* newComponent = new DiffEquations(model);
	try {
		newComponent->_loadInstance(fields);
	} catch (const std::exception& e) {

	}
	return newComponent;
}

ModelDataDefinition* DiffEquations::NewInstance(Model* model, std::string name) {
	return new DiffEquations(model, name);
}

//
// protected: //! virtual method that must be overriden
//

bool DiffEquations::_loadInstance(PersistenceRecord *fields) {
	bool res = ModelComponent::_loadInstance(fields);
	if (res) {
		_precision = fields->loadField("precision", DEFAULT.precision);
		_maxSteps = fields->loadField("maxSteps", DEFAULT.maxSteps);
		_finalTime = fields->loadField("finalTime", DEFAULT.finalTime);

		_equations->clear();
		std::string equationsStr = fields->loadField("equations", "");
		if (!equationsStr.empty()) {
			size_t pos = 0;
			size_t delimPos;
			while ((delimPos = equationsStr.find(";", pos)) != std::string::npos) {
				_equations->insert(equationsStr.substr(pos, delimPos - pos));
				pos = delimPos + 1;
			}
			if (pos < equationsStr.length()) {
				_equations->insert(equationsStr.substr(pos));
			}
		}

		_stateVariableNames->clear();
		std::string stateVarsStr = fields->loadField("stateVariableNames", "");
		if (!stateVarsStr.empty()) {
			size_t pos = 0;
			size_t delimPos;
			while ((delimPos = stateVarsStr.find(";", pos)) != std::string::npos) {
				_stateVariableNames->insert(stateVarsStr.substr(pos, delimPos - pos));
				pos = delimPos + 1;
			}
			if (pos < stateVarsStr.length()) {
				_stateVariableNames->insert(stateVarsStr.substr(pos));
			}
		}

		std::string cppCompilerName = fields->loadField("cppCompiler", "");
		_cppCompiler = nullptr;
		if (!cppCompilerName.empty()) {
			ModelDataDefinition* def = _parentModel->getDataManager()->getDataDefinition(
					Util::TypeOf<CppCompiler>(), cppCompilerName);
			_cppCompiler = dynamic_cast<CppCompiler*>(def);
		}
	}
	return res;
}

void DiffEquations::_saveInstance(PersistenceRecord *fields, bool saveDefaultValues) {
	ModelComponent::_saveInstance(fields, saveDefaultValues);

	std::string equationsStr = "";
	for (unsigned int i = 0; i < _equations->size(); i++) {
		equationsStr += _equations->getAtRank(i);
		if (i < _equations->size() - 1) {
			equationsStr += ";";
		}
	}
	fields->saveField("equations", equationsStr, "", saveDefaultValues);

	std::string stateVarsStr = "";
	for (unsigned int i = 0; i < _stateVariableNames->size(); i++) {
		stateVarsStr += _stateVariableNames->getAtRank(i);
		if (i < _stateVariableNames->size() - 1) {
			stateVarsStr += ";";
		}
	}
	fields->saveField("stateVariableNames", stateVarsStr, "", saveDefaultValues);
	fields->saveField("precision", _precision, DEFAULT.precision, saveDefaultValues);
	fields->saveField("maxSteps", _maxSteps, DEFAULT.maxSteps, saveDefaultValues);
	fields->saveField("finalTime", _finalTime, DEFAULT.finalTime, saveDefaultValues);
	fields->saveField("cppCompiler",
	                  _cppCompiler != nullptr ? _cppCompiler->getName() : std::string(""),
	                  std::string(""),
	                  saveDefaultValues);
}

void DiffEquations::_onDispatchEvent(Entity* entity, unsigned int inputPortNumber) {
	(void)inputPortNumber;
	traceSimulation(this, "Invoking cpp user code for dispatchEvent");
	const unsigned int n = _equations->size();
	if (n == 0) {
		this->_parentModel->sendEntityToComponent(entity, this->getConnectionManager()->getFrontConnection());
		return;
	}
	std::vector<double> stateVars(n, 0.0);
	for (unsigned int i = 0; i < n; i++) {
		if (_stateVariableNames->size() > i) {
			Variable* stateVar = dynamic_cast<Variable*>(_parentModel->getDataManager()->getDataDefinition(
			        Util::TypeOf<Variable>(), _stateVariableNames->getAtRank(i)));
			if (stateVar != nullptr) {
				stateVars[i] = stateVar->getValue();
			}
		}
	}
	const double t0 = 0.0;
	const double tTarget = _parentModel->getSimulation()->getSimulatedTime();
	double step = (_maxSteps > 0.0) ? ((tTarget - t0) / _maxSteps) : 0.01;
	if (step <= 0.0) {
		step = 0.01;
	}
	try {
		if (dispatchEvent_SharedLibHandler != nullptr) {
			dispatchEvent_SharedLibHandler(stateVars.data(), static_cast<int>(n), t0, tTarget, step);
			_valuesOnFinalTime->clear();
			for (unsigned int i = 0; i < n; i++) {
				_valuesOnFinalTime->insert(stateVars[i]);
				if (_stateVariableNames->size() > i) {
					Variable* stateVar = dynamic_cast<Variable*>(_parentModel->getDataManager()->getDataDefinition(
					        Util::TypeOf<Variable>(), _stateVariableNames->getAtRank(i)));
					if (stateVar != nullptr) {
						stateVar->setValue(stateVars[i]);
					}
				}
			}
		}
	} catch (const std::exception& e) {
		(void)e;
	}
	this->_parentModel->sendEntityToComponent(entity, this->getConnectionManager()->getFrontConnection());
}


//
// protected: //! virtual methods that could be overriden by derived classes, if needed
//


bool DiffEquations::_check(std::string& errorMessage) {
	bool resultAll = true;
	std::string name = this->getName();

	if (_equations->size() == 0) {
		errorMessage += "DiffEquations \"" + name + "\": no equations defined.";
		return false;
	}
	if (_stateVariableNames->size() > 0 && _stateVariableNames->size() != _equations->size()) {
		errorMessage += "DiffEquations \"" + name
		                + "\": stateVariableNames count must match equations count.";
		return false;
	}
	if (_cppCompiler == nullptr) {
		errorMessage += "DiffEquations \"" + name + "\": CppCompiler not set.";
		return false;
	}

	const std::vector<std::string> stateVariableNames =
	        resolveStateVariableNames(_stateVariableNames, _equations->size());
	const std::string sourceCode = buildDiffEquationsSource(name, stateVariableNames, _equations, _maxSteps);

	// save the code for the compiler
	std::string _sourceFilename = "./" + name + ".cpp";
	std::string _outputFilename = "./" + name + ".so";
	try {
		trace("Saving source file \"" + _sourceFilename + "\"");
		std::ofstream outfile(_sourceFilename);
		outfile << sourceCode;
		outfile.close();
	} catch (const std::exception& e) {
		resultAll = false;
        errorMessage.append("Error saving source code to compile: ");// + e.what();
        errorMessage.append(e.what());
	}
	// if saved, compile
	if (resultAll) {
		trace("Compiling source file \"" + _sourceFilename + "\"");
		_cppCompiler->setSourceFilename(_sourceFilename);
		_cppCompiler->setOutputFilename(_outputFilename);
		std::string objectFiles = "";
		_cppCompiler->setObjectFiles(objectFiles);
		CppCompiler::CompilationResult result = _cppCompiler->compileToDynamicLibrary();
		if (!result.success) {
			resultAll = false;
			if (result.compilationErrOutput != "")
                errorMessage += result.compilationErrOutput;
			else
                errorMessage += result.compilationStdOutput;
		}
	}
	// if compiled, load dynamic library
	if (resultAll) {
		_cppCompiler->unloadLibrary();
		trace("Loading dynamic library \"" + _outputFilename + "\"");
		resultAll = _cppCompiler->loadLibrary(errorMessage);
		if (!resultAll) {
            errorMessage += ". Error loading dynamic library.";
		}
	}
	// if dynamic library loaded, then vinculate pointers to loaded functions
	if (resultAll) {
		trace("Vinculating dynamic library functions");
		try {
			void* handle = _cppCompiler->getDynamicLibraryHandler();
			dispatchEvent_SharedLibHandler = (diffEquationsOnDispatchEvent_t)dlsym(handle, "onDispatchEvent");
			//initBetweenReplications_SharedLibHandler = (initBetweenReplications_t)dlsym(handle, "initBetweenReplications");
		} catch (...) {
			resultAll = false;
            errorMessage += "Error vinculating library functions";
		}
	} else {
		dispatchEvent_SharedLibHandler = nullptr;
		//initBetweenReplications_SharedLibHandler = nullptr;
	}
	return resultAll;
}


/*
ParserChangesInformation* DiffEquations::_getParserChangesInformation() {
	ParserChangesInformation* changes = new ParserChangesInformation();
	//@TODO not implemented yet
	changes->getassignments().append("");
	changes->getexpressionProductions().append("");
	changes->getexpressions().append("");
	changes->getfunctionProdutions().append("");
	changes->getassignments().append("");
	changes->getincludes().append("");
	changes->gettokens().append("");
	changes->gettypeObjs().append("");
	return changes;
}
*/

/*
void DiffEquations::_initBetweenReplications() {
	try {
		if (initBetweenReplications_SharedLibHandler != nullptr) {
			initBetweenReplications_SharedLibHandler(_parentModel);
		} else {
			traceError("Could not call function in shared library for "+getName());
		}
	} catch (...) {
		traceError("Could not call function in shared library for "+getName());
	}
}
*/


//void DiffEquations::_createAttachedAttributes() {}


/*
void DiffEquations::_addSimulationControl(SimulationControl* property) {
}
*/

// void DiffEquations::_createInternalStatisticReporters() { }

void DiffEquations::_createEditableDataDefinitions() {
	if (_cppCompiler == nullptr) {
		_cppCompiler = new CppCompiler(_parentModel, getName() + ".CppCompiler");
		_cppCompiler->setSourceFilename(getName() + ".cpp");
		_cppCompiler->setOutputFilename(getName() + ".so");
	}
	if (_cppCompiler != nullptr) {
		_mandatoryNonEditableDataDefinitionInsert("CppCompiler", _cppCompiler);
	} else {
		_mandatoryNonEditableDataDefinitionRemove("CppCompiler");
	}
}
