.PHONY: build debug release clean

build:
	./build_qtgui.sh

debug:
	./build_qtgui.sh --config Debug

release:
	./build_qtgui.sh --config Release

clean:
	rm -rf build/cmake-debug build/cmake-release build/cmake-relwithdebinfo build/cmake-minsizerel
