#!/usr/bin/env python3
"""
Generate gtest inventory tests for every method declaration found in
source/kernel/simulator headers.

The goal is to provide a scalable scaffold so each class/method has a
corresponding unit-test entry that can be progressively implemented.
"""

from __future__ import annotations

import argparse
import pathlib
import re
from dataclasses import dataclass


@dataclass(frozen=True)
class MethodEntry:
    header: str
    class_name: str
    signature: str


CLASS_RE = re.compile(r"^\s*class\s+([A-Za-z_]\w*)\b")
METHOD_RE = re.compile(r"\(")


def _sanitize_identifier(text: str) -> str:
    out = re.sub(r"[^A-Za-z0-9_]", "_", text)
    out = re.sub(r"_+", "_", out).strip("_")
    if not out:
        out = "unnamed"
    if out[0].isdigit():
        out = f"m_{out}"
    return out


def _is_method_candidate(line: str) -> bool:
    stripped = line.strip()
    if not stripped or stripped.startswith("//"):
        return False
    if "(" not in stripped or ")" not in stripped:
        return False
    if stripped.startswith(("if ", "for ", "while ", "switch ")):
        return False
    if stripped.startswith(("typedef ", "using ", "friend ")):
        return False
    if stripped.startswith("template"):
        return False
    if stripped.endswith("{"):
        return False
    return stripped.endswith(";")


def parse_header(path: pathlib.Path) -> list[MethodEntry]:
    methods: list[MethodEntry] = []
    current_class: str | None = None
    in_public = False
    brace_depth = 0

    for raw_line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw_line.strip()

        class_match = CLASS_RE.match(raw_line)
        if class_match and "{" in raw_line:
            current_class = class_match.group(1)
            in_public = False
            brace_depth = raw_line.count("{") - raw_line.count("}")
            continue

        if current_class is None:
            continue

        brace_depth += raw_line.count("{") - raw_line.count("}")
        if brace_depth <= 0:
            current_class = None
            in_public = False
            continue

        if line.startswith("public:"):
            in_public = True
            continue
        if line.startswith(("private:", "protected:")):
            in_public = False
            continue

        if not in_public:
            continue

        if _is_method_candidate(raw_line) and METHOD_RE.search(raw_line):
            signature = " ".join(line.split())
            methods.append(
                MethodEntry(
                    header=path.name,
                    class_name=current_class,
                    signature=signature,
                )
            )

    return methods


def generate_test_source(methods: list[MethodEntry]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.")
    lines.append("// Generated by tools/generate_kernel_simulator_test_stubs.py")
    lines.append("#include <gtest/gtest.h>")
    lines.append("")
    lines.append("namespace {")
    lines.append("")

    for idx, method in enumerate(methods, start=1):
        test_name = _sanitize_identifier(f"{method.class_name}_{idx}")
        lines.append(f'TEST(KernelSimulatorMethodInventory, {test_name}) {{')
        lines.append(f"    // {method.header} :: {method.class_name} :: {method.signature}")
        lines.append("    SUCCEED();")
        lines.append("}")
        lines.append("")

    lines.append("}  // namespace")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--headers-dir", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    headers = sorted(args.headers_dir.glob("*.h"))
    all_methods: list[MethodEntry] = []
    for header in headers:
        all_methods.extend(parse_header(header))

    output_text = generate_test_source(all_methods)
    args.output.write_text(output_text, encoding="utf-8")
    print(f"Generated {len(all_methods)} method inventory tests at {args.output}")


if __name__ == "__main__":
    main()
